GET http://localhost:3015/api/hospitals

###
POST http://localhost:3015/register
Content-Type:  application/json

{
    "name": "Doctor House5",
    "username": "AwesomeUser7",
    "password": "abcABC123!"
}

###
POST http://localhost:3015/login
Content-Type:  application/json

{
    "username": "AwesomeUser7",
    "password": "abcABC123!"
}

###
GET http://localhost:3015/api/users

###
GET http://localhost:3015/api/hospitals

###
//You have to update the User ID up in the link, and below the hospital IDs
//You can get the IDs from the two GET requests above!
//ADDED JWT TOKEN, TEST WON'T WORK without it
PATCH http://localhost:3015/updateuser/63d7de20e22bca2c9ef5b25b
Content-Type:  application/json

{
    "password": "abcABC123!"
}

###
GET http://localhost:3015/api/users

###
GET http://localhost:3015/api/hospitals

###
GET http://localhost:3015/api/stock

###
POST http://localhost:3015/api/order
//You need to update user, hospital and item ID
//you can get the IDs from the 3 get requests above!
Content-Type:  application/json

{
    "user": "63d7de20e22bca2c9ef5b25d",
    "hospital": "63d7de20e22bca2c9ef5b243",
    "goods": [
        {
            "item": "63d7de20e22bca2c9ef5b258",
            "quantity": 100
        }
    ]
}

###
GET http://localhost:3015/api/order
//You need to update user, hospital and item ID
//you can get the IDs from the 3 get requests above!